# CP1404/CP5632 Practical - Christian Torrisi
# Walkthrough Example - Box Layout Demo exercise


BoxLayout:
    orientation: 'vertical'
    Button:
        text: 'Clear'
        on_press: app.clear_all()
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)